from __future__ import annotations

from .logement import FORMAT_SYSTEM, LOGEMENT_EXTRACT_SYSTEM, LOGEMENT_INFO_SYSTEM, LOGEMENT_SCHEMA
from .rag import RAG_MIN_SCORE, RAG_SYSTEM
from .routing import CLASSIFY_SCHEMA, CLASSIFY_SYSTEM, CONFIDENCE_THRESHOLD, RAG_SECTIONS, SECTIONS
from .stations import STATIONS_EXTRACT_SYSTEM, STATIONS_INFO_SYSTEM, STATIONS_SCHEMA
